### ISSUE TITLE
ERROR: Failed to resolve: com.github.AsynctaskCoffee:VideoLayout:1.0

### ISSUE THREAD

**Issue by emailsubjekt** [AsynctaskCoffee/VideoLayout#3]
I added your library to gradle 
    implementation 'com.github.AsynctaskCoffee:VideoLayout:1.0'
and in build gradle 
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }

    }

and got this error 

ERROR: Failed to resolve: com.github.AsynctaskCoffee:VideoLayout:1.0

**Comment by emailsubjekt** [comment]
Nevermind, it needed to be in the bottom repositories

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }


    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by AsynctaskCoffee** [comment]
I think you solved your issue without my help :) I am so sorry for not replying it earlier. Enjoy :)

**Comment by Clopma** [comment]
I have the same problem and I don't understand what 'in the bottom repositories' means.

**Comment by AsynctaskCoffee** [comment]
Add maven { url 'https://jitpack.io' } into gradle and make sure you have internet connection while sync

**Comment by Clopma** [comment]
It is not working. I don't have much experience with gradle. I have build.gradle (project):

```
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.2"
    }
}

allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
Then, in the build.gradle (module) file i have:

```
dependencies {
    implementation 'com.github.AsynctaskCoffee:VideoLayout:1.3'
}
```

I also had to change settings.gradle file from RepositoriesMode.FAIL_ON_PROJECT_REPOS to RepositoriesMode.PREFER_SETTINGS

It is syncing and building ok but It is not detecting the dependency:

![image](https://user-images.githubusercontent.com/47386922/134239424-e53fc42a-3aa2-4857-88eb-fdf0f60e56ca.png)

**Comment by AsynctaskCoffee** [comment]
I think you missed buildscript -> repositories part. 

```
buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.2"
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven {url 'https://developer.huawei.com/repo/'}
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```


try this and let me know I am here for a while lets fix this issue :)

**Comment by Clopma** [comment]
First of all, thank you very much for your help.

Well, it is not there at the top because I deleted it a while ago trying things, but yes, that was my first approach.  I just replaced all the file with that code you just posted but it didn't fix it. Any ideas?

**Comment by Clopma** [comment]
![image](https://user-images.githubusercontent.com/47386922/134241112-65e1a858-c664-4cfc-9129-d31927003e46.png)

**Comment by AsynctaskCoffee** [comment]
Did you activate offline grade ? 

Check;
https://stackoverflow.com/a/31235328/13706694


If yes you have to disable it.

**Comment by Clopma** [comment]
I don't have that setting under properties
![image](https://user-images.githubusercontent.com/47386922/134243095-e47cfd4e-5038-4086-ab70-92e4273402ff.png)
There's the offline mode toggle button on the gradle tab, which it's not activated:
![image](https://user-images.githubusercontent.com/47386922/134243245-98451680-0d5a-49e1-b160-49a4562f7a00.png)
Also I have other dependencies (not maven) that worked fine so I think it is not a connectivity thing.

**Comment by Clopma** [comment]
Ok I fixed it

(editing)

**Comment by AsynctaskCoffee** [comment]
Can you send me the gradle files via mail ? Or if your project public could you send me the access ?

**Comment by AsynctaskCoffee** [comment]
> Ok I fixed it
> 
> (editing)

tu est parfait 🚀 🎸  Lets share it for help to other I also wonder the solution 🦖

**Comment by AsynctaskCoffee** [comment]
Then I'm closing this issue in your honor. Happy coding.

**Comment by Clopma** [comment]
Ok I think I went too quick... For a moment the error disapeared but It was not fixed just reloading I'm sorry 😢 I will keep trying and see what happend exactly.

**Comment by AsynctaskCoffee** [comment]
Lets send me the code via GitHub I will check is there any gradle problem.

**Comment by Clopma** [comment]
Ok, I just created a repo
https://github.com/Clopma/ChupitoGratisApp

The layout is in activity_login.xml

**Comment by AsynctaskCoffee** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/47759937/134249719-4b4eb060-8aa9-4ec6-8a4c-d61e8dd2f297.png">

![image](https://user-images.githubusercontent.com/47759937/134249348-e3329b05-80a9-4e23-bb10-46e9e234d214.png)

![image](https://user-images.githubusercontent.com/47759937/134249390-854f5bc0-5fc1-4769-9527-287e370f82df.png)

![image](https://user-images.githubusercontent.com/47759937/134249438-3c2d5729-f459-4e5e-b016-9accbaa1f628.png)

![image](https://user-images.githubusercontent.com/47759937/134249485-94b7ba60-1687-41ea-9cb3-e0ff99f37028.png)




------

```

apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.carloslopezmari.myapplication"
        minSdkVersion 26
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resConfigs "en", "US"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
    implementation 'androidx.navigation:navigation-fragment:2.3.5'
    implementation 'androidx.navigation:navigation-ui:2.3.5'
    implementation 'com.google.android.gms:play-services-location:18.0.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.shuhart.stepview:stepview:1.5.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'com.github.AsynctaskCoffee:VideoLayout:1.6'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```


and



```
buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven {url 'https://developer.huawei.com/repo/'}
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```


Enjoy ✨

**Comment by AsynctaskCoffee** [comment]
As I saw there is a lot of typos in ur gradle.  I hope it works 👓

**Comment by Clopma** [comment]
Oh It worked, thank you very much!

I tried every one of your changes separately and what mattered at the end was deleting the `dependencyResolutionManagement` from `setting.gradle`, I don't know exactly why but that was causing it to break!
![image](https://user-images.githubusercontent.com/47386922/134251255-6f4bf2df-5f7e-4196-87b8-c7b702972c82.png)

Thank you very much again for your time!

**Comment by AsynctaskCoffee** [comment]
You are welcome my friend 🤩
