### ISSUE TITLE
url format

### ISSUE THREAD

**Issue by matteogabella** [AsynctaskCoffee/VideoLayout#4]
hi, i tried successfully to use your Layout with the file in assets... but when i try with URL, i obtain only a blank screen... in which format i have to provide the url?
thank you

**Comment by AsynctaskCoffee** [comment]
Hi sorry for late reply, Url should ends with .mp4 or any other video format. And video page must supports to play it.

For example: This video should play http://techslides.com/demos/sample-videos/small.mp4

If you have other questions just ask! Thank you!

**Comment by matteogabella** [comment]
thank you!
i think android apps need **https**, instead of **http** though
this is working 
https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4
thanks!
